# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.6.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box      = "prognet/winweb"
  config.vm.hostname = "web01"
  config.vm.communicator = "winrm"
  config.vm.network "private_network", ip: "172.28.128.4"
  #config.vm.network "private_network", type: "dhcp"

  config.windows.set_work_network = true

  config.vm.network :forwarded_port, guest: 3389, host: 33891
  config.vm.network :forwarded_port, guest: 5985, host: 59851, id: "winrm", auto_correct: true
  config.vm.network :forwarded_port, guest: 22, host: 22221

  config.vm.provider :virtualbox do |vb|
    #vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", 768]
    vb.customize ["modifyvm", :id, "--cpus", 1]
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end
end